#!/usr/bin/env node
// v150 D — the "which checks for which change" table, GENERATED from scripts/checks.json.
//
// It replaces the hand-kept "Verify before committing" table that CLAUDE.md used to carry. Writes the
// appendix of docs/CHECKS.md between the CHECKS-TABLE markers (appending the markers the first time).
//   node scripts/checks-table.mjs          rewrite the appendix
//   node scripts/checks-table.mjs --check  exit 1 if the appendix is stale (nothing written)
// Suite fields read: desc, checks, anchors, files, and the optional by-hand notes `steps` (builds to
// run first), `variants` (env-var runs) and `look` (screenshot utilities) — the runner ignores those.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const M = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/checks.json'), 'utf8'))
const DOC = path.join(ROOT, 'docs/CHECKS.md')
const BEGIN = '<!-- CHECKS-TABLE:BEGIN (generated by scripts/checks-table.mjs from scripts/checks.json — do not edit by hand) -->'
const END = '<!-- CHECKS-TABLE:END -->'

const cell = s => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ')
const code = a => a.map(x => '`' + x + '`').join(', ')
const rows = []
for (const [name, s] of Object.entries(M.suites)) {
  const notes = []
  if (s.steps?.length) notes.push('first: ' + s.steps.join('; '))
  if (s.variants?.length) notes.push('also: ' + s.variants.join('; '))
  if (s.look?.length) notes.push('look: ' + s.look.join('; '))
  const pulls = [...(s.anchors || []).map(a => '`' + a + '`'), ...(s.files || []).map(f => '`' + f + '`')]
  rows.push(`| \`${name}\` | ${cell(s.desc || '')} | ${code(s.checks || [])} | ${cell(pulls.join(', ') || '—')} | ${cell(notes.join(' · ') || '')} |`)
}
const n = Object.keys(M.checks).length
const table = [
  BEGIN,
  '',
  '## Appendix — which suite for which change (generated)',
  '',
  `Every suite in \`scripts/checks.json\` (${Object.keys(M.suites).length} suites, ${n} checks; \`fast\` and \`full\` are`,
  'generated by the runner). `node scripts/run-checks.mjs --since main` picks these for you from the diff; run',
  'one by name with `node scripts/run-checks.mjs <suite> --jobs 4`. "Pulled by" is what `--since` matches (banner',
  'tags / text in a changed hunk, or a changed file glob). The last column is by hand: builds to run first,',
  'env-var variants, and screenshot utilities to LOOK with — the runner does none of those.',
  '',
  '| suite | for a change to… | checks | pulled by | by hand |',
  '|---|---|---|---|---|',
  ...rows,
  '',
  END,
].join('\n')

const doc = fs.readFileSync(DOC, 'utf8')
const i = doc.indexOf(BEGIN.slice(0, 24)), k = doc.indexOf(END)
const next = i >= 0 && k > i ? doc.slice(0, i) + table + doc.slice(k + END.length) : doc.replace(/\s*$/, '\n\n') + table + '\n'
if (process.argv.includes('--check')) {
  const fresh = next === doc
  console.log(`${fresh ? 'ok  ' : 'FAIL'} docs/CHECKS.md's appendix matches scripts/checks.json`)
  console.log(JSON.stringify({ pass: fresh ? 1 : 0, fail: fresh ? 0 : 1, pageErrors: 0 }))
  process.exit(fresh ? 0 : 1)
}
fs.writeFileSync(DOC, next)
console.log(`wrote the appendix: ${rows.length} suites`)
